#!/bin/sh -xe

trap 'cp -r ../node_modules .; rm -rf ../public ../node_modules ../doc' INT TERM EXIT

brunch build --optimize
codo --private ./app/
cp -r public ../
cp -r doc ../
cp -r node_modules ../
git stash -u
git checkout gh-pages
rm -rfv *
cp -rv ../public .
cp -rv ../doc .
git add --all
git commit -m 'Update site'
git push
git checkout master
git stash pop
